name: CI  # 任务名称

# 事件
on:
  # push hexo 分支的时候触发；
  push:
    branches: [ hexo ]

# 工作流运行由一个或多个任务组成，这些任务按顺序或并行运行
jobs:
  # 工作流包含一个 build 的任务
  build:
    # build 任务运行环境为 ubuntu 最新版
    runs-on: ubuntu-latest

    # 输出映射
    outputs:
      test: 我还不会动态传参
    
    # 任务步骤
    steps:
      # actions 拉代码到当前环境
      - name: git checkout
        uses: actions/checkout@v3
      
      # 设置 node 环境  如果不知道可以再 Marketplace 下搜索
      - name: install NodeJs env
        uses: actions/setup-node@v3
        # 安装 node 的具体命令
        with:
          node-version: "12.16.x"
      
      # 给项目安装依赖
      - name: npm install
        run: npm install
        
        
  
