name: CI  # 任务名称

# 事件
on:
  # push hexo 分支的时候触发；
  push:
    branches: [ hexo ]

# 工作流运行由一个或多个任务组成，这些任务按顺序或并行运行
jobs:
  # 工作流包含一个 build 的任务
  build:
    # build 任务运行环境为 ubuntu 最新版
    runs-on: ubuntu-latest

    # 输出映射
    outputs:
      test: 我还不会动态传参
    
    # 任务步骤
    steps:
      # actions 拉代码到当前环境
      - name: git checkout
        uses: actions/checkout@v3
      
      # 设置 node 环境  如果不知道可以再 Marketplace 下搜索
      - name: install NodeJs env
        uses: actions/setup-node@v3
        # 安装 node 的具体命令
        with:
          node-version: "12.16.0"

      - name: cd object and install and build
        run: |
          cd idrnyu.github.io
          npm install
          npx hexo clean
          npx hexo g
      
      # 给项目安装依赖
      # - name: npm install
      #   run: npm install
      
      # 清除缓存
      # - name: npx hexo clean
      #   run: npx hexo clean

      # 生成静态网页
      # - name: npx hexo g
      #   run: npx hexo g

      # 开始部署
      # - name: npx hexo d
      #   run: npx hexo d

      # 将打包好的public文件复制到项目
      - name: Upload the public file to the master branch
        # Deploy to GitHub Pages
        # https://github.com/marketplace/actions/deploy-to-github-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.IDRNYU_CI_TOKEN }}
          branch: master #部署提交到的分支
          folder: ./idrnyu.github.io/public # 打包好的目录

  # 工作流中又包含了一个 console-test 任务，依赖 build 任务
  console-test:
    runs-on: ubuntu-latest
    needs: [build] # 任务依赖关系

    steps:
      - name: 输出上下文
        run: |
          pwd
          echo ${{ needs.build.outputs.test }}
          exit
        
        
  